spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: lootopia
          uri: lb://lootopia
          predicates:
            - Path=/lootopia/**
          filters:
            - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
