spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: lootopia
          uri: lb://lootopia
          predicates:
            - Path=/lootopia/**
          filters:
            - StripPrefix=1
        - id: locationserv
          uri: lb://locationserv
          predicates:
            - Path=/locationserv/**
          filters:
            - StripPrefix=1
        - id: paymentserv
          uri: lb://paymentserv
          predicates:
            - Path=/paymentserv/**
          filters:
            - StripPrefix=1
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  forward-headers-strategy: framework
  port: ${GATEWAY_PORT}

eureka:
  client:
    service-url:
      defaultZone: http://eureka:${EUREKA_PORT}/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  show-default-server: false
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Lootopia
        url: /lootopia/v3/api-docs
      - name: Location service
        url: /locationserv/v3/api-docs
      - name: Payment service
        url: /paymentserv/v3/api-docs
  servers:
    url: http://localhost:${GATEWAY_PORT}
