spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: lootopia
          uri: lb://lootopia
          predicates:
            - Path=/lootopia/**
          filters:
            - StripPrefix=1
        - id: locationserv
          uri: lb://locationserv
          predicates:
            - Path=/locationserv/**
          filters:
            - StripPrefix=1

server:
  port: ${GATEWAY_PORT}

eureka:
  client:
    service-url:
      defaultZone: http://eureka:${EUREKA_PORT}/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Lootopia
        url: http://localhost:${GATEWAY_PORT}/lootopia/v3/api-docs
      - name: Location service
        url: http://localhost:${GATEWAY_PORT}/location/v3/api-docs
